CONSOLE_ENABLE = no
COMMAND_ENABLE = no
ORYX_ENABLE = yes
RGB_MATRIX_CUSTOM_KB = yes
SPACE_CADET_ENABLE = no
COMBO_ENABLE = yes
DYNAMIC_TAPPING_TERM_ENABLE = yes
LAYER_LOCK_ENABLE = yes
PRECISION_TRACKPAD_ENABLE = yes
PRECISION_TRACKPAD_DRIVER = navigator_trackpad

# ---

KEY_OVERRIDE_ENABLE = yes
